image: docker

stages:
  - build
  - test

before_script:
  - export SHA=$(git rev-parse HEAD)
  - export CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - openssl aes-256-cbc -K $encrypted_a16a01bc6a49_key -iv $encrypted_a16a01bc6a49_iv -in multi-k8s-serice-account-token1.json.enc -out multi-k8s-serice-account-token1.json -d
  - curl http://sdk.cloud.google.com |bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-serice-account-token1.json
  - gcloud config set project multi-k8s-339919
  - gcloud config set compute/zone asia-south1-a
  - gcloud container clusters get-credentials  multi-k8s
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t "$DOCKER_USERNAME"/multi-k8s -f ./client/Dockerfile.dev ./client
  - docker run -e CI=true "$DOCKER_USERNAME"/multi-k8s npm test
