sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_a16a01bc6a49_key -iv $encrypted_a16a01bc6a49_iv -in multi-k8s-serice-account-token1.json.enc -out multi-k8s-serice-account-token1.json -d
  - curl http://sdk.cloud.google.com |bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file multi-k8s-serice-account-token1.json
  - gcloud config set project multi-k8s-339919
  - gcloud config set compute/zone asia-south1-a
  - gcloud container clusters get-credentials  multi-k8s
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t lpremraj/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true lpremraj/react-test npm test

after_success:
  - docker build -t lpremraj/multi-client-10-14 ./client
  - docker build -t lpremraj/multi-nginx-10-14 ./nginx
  - docker build -t lpremraj/multi-server-10-14 ./server
  - docker build -t lpremraj/multi-worker-10-14 ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # Take those images and push them to docker hub
  - docker push lpremraj/multi-client-10-14
  - docker push lpremraj/multi-nginx-10-14
  - docker push lpremraj/multi-server-10-14
  - docker push lpremraj/multi-worker-10-14
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
